version: '3'

services:

  postgres:
    container_name:  postgres-db
    image:           postgres:9.6.6
    restart: "always"
    ports:
      - 5432:5432 # Bind host port 5432 to PostgreSQL port 5432
    volumes:
      - ../postgres:/var/lib/postgresql/data
    env_file: ../.env
    environment:
      - LC_ALL=C.UTF-8


  redis:
    image: redis:4.0.11
    restart: "on-failure"
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ../redisdb:/var/lib/redis

#  elasticsearch:
#    restart: "always"
#    container_name: elasticsearch
#    image: blacktop/elasticsearch
#    ports:
#      - "9200:9200"