# Generated by Django 3.0.4 on 2020-05-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='text',
            field=models.TextField(blank=True, verbose_name='Content'),
        ),
    ]
