# Generated by Django 3.0.4 on 2020-04-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_category_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.CharField(blank=True, help_text='Example /about/ -page url', max_length=255, null=True, verbose_name='URL'),
        ),
    ]
