# Generated by Django 3.0.4 on 2020-05-15 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200504_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_editors_choice',
            field=models.BooleanField(default=False, verbose_name="Editor's choice"),
        ),
        migrations.CreateModel(
            name='HomePageSectionsSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fifth_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fifth_section_categories', to='news.Category', verbose_name='Fifth section category')),
                ('first_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_section_categories', to='news.Category', verbose_name='First section category')),
                ('fourth_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fourth_section_categories', to='news.Category', verbose_name='Fourth section category')),
                ('second_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_section_categories', to='news.Category', verbose_name='Second section category')),
                ('sixth_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sixth_section_categories', to='news.Category', verbose_name='Sixth section category')),
                ('third_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_section_categories', to='news.Category', verbose_name='Third section category')),
            ],
        ),
    ]
