# Generated by Django 3.0.4 on 2020-05-15 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200515_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesectionssettings',
            name='right_corner_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_corner_category', to='news.Category', verbose_name='Right Corner section category'),
        ),
        migrations.AddField(
            model_name='post',
            name='show_in_home_page',
            field=models.BooleanField(default=False, verbose_name='Show in Home page'),
        ),
        migrations.AlterField(
            model_name='homepagesectionssettings',
            name='fifth_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fifth_section_category', to='news.Category', verbose_name='Fifth section category'),
        ),
        migrations.AlterField(
            model_name='homepagesectionssettings',
            name='first_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_section_category', to='news.Category', verbose_name='First section category'),
        ),
        migrations.AlterField(
            model_name='homepagesectionssettings',
            name='fourth_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fourth_section_category', to='news.Category', verbose_name='Fourth section category'),
        ),
        migrations.AlterField(
            model_name='homepagesectionssettings',
            name='second_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_section_category', to='news.Category', verbose_name='Second section category'),
        ),
        migrations.AlterField(
            model_name='homepagesectionssettings',
            name='sixth_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sixth_section_category', to='news.Category', verbose_name='Sixth section category'),
        ),
        migrations.AlterField(
            model_name='homepagesectionssettings',
            name='third_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_section_category', to='news.Category', verbose_name='Third section category'),
        ),
    ]
