# Generated by Django 3.0.4 on 2020-05-17 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20200515_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesectionssettings',
            name='seventh_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seventh_section_category', to='news.Category', verbose_name='Seventh section category'),
        ),
        migrations.AddField(
            model_name='homepagesectionssettings',
            name='top_left_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_left_category', to='news.Category', verbose_name='Top left section category'),
        ),
        migrations.AddField(
            model_name='homepagesectionssettings',
            name='top_right_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_right_category', to='news.Category', verbose_name='Top right section category'),
        ),
    ]
