# Generated by Django 3.0.4 on 2020-05-18 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20200517_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagesectionssettings',
            name='top_left_section',
        ),
        migrations.RemoveField(
            model_name='homepagesectionssettings',
            name='top_right_section',
        ),
    ]
