# Generated by Django 3.0.4 on 2020-05-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20200518_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='top_news',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Top Left'), (2, 'Top Right')], null=True, verbose_name='Top news'),
        ),
    ]
