# Generated by Django 3.0.4 on 2020-05-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_post_is_multimedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_saved',
            field=models.BooleanField(default=False, verbose_name='Is saved'),
        ),
    ]
