# Generated by Django 3.0.4 on 2020-05-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_post_is_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End date'),
        ),
    ]
