# Generated by Django 3.0.4 on 2020-05-23 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_post_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_saved',
        ),
    ]
