# Generated by Django 3.0.4 on 2020-05-23 12:36

import core.options.tools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_remove_post_is_saved'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenShot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(upload_to=core.options.tools.user_directory_path, verbose_name='Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ScreenShot',
                'verbose_name_plural': 'ScreenShots',
            },
        ),
    ]
