# Generated by Django 3.0.4 on 2020-05-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='video',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Video'),
        ),
    ]
