# Generated by Django 3.0.4 on 2020-06-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_comment_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesectionssettings',
            name='is_liked_by_auth_user',
            field=models.BooleanField(default=False, verbose_name='Liked by Auth User'),
        ),
    ]
