# Generated by Django 3.0.4 on 2020-06-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_homepagesectionssettings_is_liked_by_auth_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagesectionssettings',
            name='is_liked_by_auth_user',
        ),
        migrations.AddField(
            model_name='post',
            name='is_liked_by_auth_user',
            field=models.BooleanField(default=False, verbose_name='Liked by Auth User'),
        ),
    ]
