# Generated by Django 3.0.4 on 2020-06-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_auto_20200603_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_disliked_by_auth_user',
            field=models.BooleanField(default=False, verbose_name='Disliked by Auth User'),
        ),
    ]
