# Generated by Django 3.0.4 on 2020-06-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_auto_20200603_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_saved_by_auth_user',
            field=models.BooleanField(default=False, verbose_name='Saved by Auth User'),
        ),
    ]
