# Generated by Django 3.0.4 on 2020-05-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='show_in_home_page',
            field=models.BooleanField(default=False, verbose_name='Show in Home page'),
        ),
    ]
