# Generated by Django 3.0.4 on 2020-04-17 11:04

import core.options.tools
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import user.model_managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_type', models.IntegerField(choices=[(1, 'User'), (2, 'Reporter'), (3, 'Editor'), (4, 'Admin')], default=1, verbose_name='User type')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Last Name')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=core.options.tools.user_directory_path, verbose_name='Avatar')),
                ('phone_number', models.CharField(blank=True, max_length=255, verbose_name='Phone Number')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last login')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('preferred_categories', models.ManyToManyField(blank=True, related_name='categories', to='news.Category', verbose_name='Preferred Categories')),
                ('saved_news', models.ManyToManyField(blank=True, related_name='saved_news', to='news.Post', verbose_name='Saved news')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', user.model_managers.MyUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuthorSocialMediaAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media', models.CharField(choices=[('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Linkedin', 'Linkedin'), ('YouTube', 'YouTube')], max_length=255, verbose_name='Social Media')),
                ('url', models.URLField(verbose_name='Url')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_account', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': "Author's Social Media Account",
                'verbose_name_plural': "Author's Social Media Accounts",
            },
        ),
    ]
