# Generated by Django 3.0.4 on 2020-05-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200515_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='profession',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Profession'),
        ),
    ]
