# Generated by Django 3.0.4 on 2020-05-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20200517_1914'),
        ('user', '0004_myuser_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='favorite_category',
            field=models.ManyToManyField(blank=True, to='news.Category', verbose_name='Favorite category'),
        ),
    ]
