# Generated by Django 3.0.4 on 2020-04-17 11:04

import core.options.tools
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Message')),
                ('send_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Send date')),
            ],
            options={
                'verbose_name': 'Contact Form',
                'verbose_name_plural': 'Contact Forms',
            },
        ),
        migrations.CreateModel(
            name='OneSignal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(max_length=255, verbose_name='User Code')),
                ('device_type', models.CharField(max_length=255, verbose_name='Device type')),
            ],
            options={
                'verbose_name': 'One Signal',
                'verbose_name_plural': 'One Signal',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright', models.TextField(blank=True, verbose_name='Copyright')),
                ('logo', models.FileField(upload_to=core.options.tools.user_directory_path, verbose_name='Website Logo')),
                ('footer_text', models.TextField(blank=True, verbose_name='Text on footer section')),
                ('footer_social_media_text', models.TextField(blank=True, verbose_name='Social media text on footer section')),
                ('search_placeholder', models.CharField(blank=True, max_length=255, verbose_name='Search placeholder')),
                ('author_widget_title', models.CharField(blank=True, max_length=255, verbose_name='Widget title on authors section')),
                ('slider_video_title', models.CharField(blank=True, max_length=255, verbose_name='Slider video title')),
                ('slider_button_title', models.CharField(blank=True, max_length=255, verbose_name='Slider button title')),
                ('item_now_playing_text', models.CharField(blank=True, max_length=255, verbose_name='Item now playing text')),
                ('terms_and_conditions', models.TextField(blank=True, verbose_name='Terms and Conditions')),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('icon', models.FileField(upload_to=core.options.tools.user_directory_path, verbose_name='Icon')),
                ('link', models.URLField(verbose_name='Link')),
                ('position', models.CharField(choices=[('Side', 'Side'), ('Header', 'Header'), ('Footer', 'Footer')], help_text='Choose the position of the Social Media Logo on the website', max_length=255, verbose_name='Position')),
            ],
            options={
                'verbose_name': 'Social Media Setting',
                'verbose_name_plural': 'Social Media Settings',
            },
        ),
    ]
